name: cobalt
version: '0.16.0'
summary: A straightforward static site generator written in Rust.
description: |
  Simple
  Cobalt will help you get up and running quickly but scales to handle your more complex cases
  Easy
  Cobalt tries to be no-hassle, from being easy to install, a workflow-centric command line, to a familiar   template language.
  Fast
  Quickly see the results of your work.

base: core18
grade: stable
confinement: strict

parts:
  cobalt:
    plugin: rust
    source: https://github.com/cobalt-org/cobalt.rs.git
    source-tag: v0.16.0
      
apps:
  cobalt:
    command: bin/cobalt
    plugs: [home, network-bind]
